server:
  port: 8089
  servlet:
    context-path: /api #web访问统一前缀
    # 打印sql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/six?characterEncoding=UTF-8&useSSL=true&serverTimezone=PRC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: sckr
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ehcache
  ehcache:
    config: classpath:ehcache.xml
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:com/bate/**/*Mapper.xml
  type-aliases-package: com.bate
baseConf:
  accessToken:
    expireTime: 2592000
logging:
  level:
    com.bate.admin.mapper: debug
