server:
  port: 8089
  servlet:
    context-path: /api #web访问统一前缀
    # 打印sql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/six?characterEncoding=UTF-8&useSSL=true&serverTimezone=PRC&autoReconnect=true
    username: sckr
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ehcache
  ehcache:
    config: classpath:ehcache.xml
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:com/bate/**/*Mapper.xml
  type-aliases-package: com.bate
baseConf:
  accessToken:
    expireTime: 2592000

upfiles:
  basePath: E:\temp\ten
  allowed: file
  fileSize: 10  #单位M
  ext:
    all: all  # 允许上传所有类型文件
    files: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip

logging:
  level:
    com.bate.admin.mapper: debug
